Fix `NullTransport.send_and_ignore`
Currently raises an exception, because the signature does not match other transports.

    TypeError: send_and_ignore() takes exactly 2 arguments (3 given)